title = "roblox-grid-based-server-sharding"  # From Git
gitRepoUrl = "https://github.com/minh-p/roblox-grid-based-server-sharding" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "minh-p"
projectName = "roblox-grid-based-server-sharding"
url = "https://docs.vhmp.dev"
baseUrl = "/roblox-grid-based-server-sharding"
tagline = "Roblox"

[footer]
style = "dark"
copyright = "Copyright Â© 2025 minh-p (Vu Huy Minh Pham). Built with Moonwave and Docusaurus"

[[footer.links]]
title = "examples"

[[footer.links.items]]
label = "example"
href = "https://example.com/"
